from __future__ import annotations
from dataclasses import dataclass
from typing import Sequence
import numpy as np
from .atom import Atom

@dataclass
class Molecule:
    atoms: List[Atom]

    @classmethod
    def from_string(cls, xyz_string: str) -> Molecule:
        lines = xyz_string.strip().splitlines()
        atoms = []
        for line in lines[2:]:
            atom = Atom.from_string(line)
            atoms.append(atom)
        return cls(atoms)
    
    def __str__(self):
        return "\n".join([str(atom) for atom in self.atoms])   # string abc das jeden wert in neue zeile schreibt

    @property
    def n_electrons(self):
       return sum([atom.n_electrons for atom in self.atoms])   # list comprehension
    
    def to_string(self) -> str:   # hier wird die xyz string generiert, die dann für die visualisierung genutzt werden kann
        lines = [str(len(self.atoms)), "Generated by Molecule Class"] 
        for atom in self.atoms:
            line = f"{atom.symbol} {atom.coord[0]:.6f} {atom.coord[1]:.6f} {atom.coord[2]:.6f}"
            lines.append(line)
        return "\n".join(lines) # string abc das jeden wert in neue zeile schreibt  

        
 